spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

management:
  security:
    user: ${management.security.user}
    pass: ${management.security.pass}

swagger:
  security:
    user: ${swagger.security.user}
    pass: ${swagger.security.pass}
