version: '3.3'
services:
  db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: 'urlshortener'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - urlshortener-database:/var/lib/mysql
volumes:
  urlshortener-database: